### ISSUE TITLE
0.15.0: missing git tag?

### ISSUE THREAD

**Issue by kloczek** [sbdchd/flake8-pie#112]
Accordimg to https://pypi.org/project/flake8-pie/ latest version is 0.15.0 however here there is no git tag for that version.

**Comment by sbdchd** [comment]
Yeah I think we kind of skipped that when we released: https://github.com/sbdchd/flake8-pie/commit/02d073ca66fdc05298792aa9f878656381ffa13a

the release process is pretty manual

**Comment by kloczek** [comment]
Thank you :)
Closing.
