### ISSUE TITLE
`prefer-simple-any-all`

### ISSUE THREAD

**Issue by sbdchd** [sbdchd/flake8-pie#71]
```python
# err
all((x.id for x in bar))
any([x.id for x in bar])


# ok
all(x.id for x in bar)
any(x.id for x in bar)
any({x.id for x in bar})
```

I thought https://github.com/adamchainz/flake8-comprehensions would check for this, but sadly it doesn't

Like technically it changes the meaning a bit, but I think it's okay

**Comment by chdsbd** [comment]
fixed via #72
